apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snowflake-ingress
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  tls:
    - hosts:
        - snowflake.dev.local
      secretName: snowflake-tls
  rules:
    - host: snowflake.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snowflake-service
                port:
                  number: 80
