apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snowflake-ingress
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  rules:
    - host: snowflake.dev.iprody
      http:
        paths:
          - path: /next-id
            pathType: Prefix
            backend:
              service:
                name: snowflake-service
                port:
                  number: 80
